In [5]:
import numpy as np


In [8]:
np.arange(12).reshape(4,3)



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
a2[1,1]


50

In [32]:
# 90을 95로 변경
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [41]:
a2[0,2] = 23
a2[0] = np.array([1, 2, 3]) # 정석
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 95]])

In [50]:
a2[0] = np.array([4, 5, 6]) # 에러 확인, array(배열)의 크기가 다름
a2 

array([[ 4,  5,  6],
       [40, 50, 60],
       [70, 80, 95]])

- 2차원 배열의 행과 열 위치 지정해서 원소 추출
 + (행의 위치1, 열의 위치1) / (행의 위치2, 열의 위치2)

In [51]:
a2

array([[ 4,  5,  6],
       [40, 50, 60],
       [70, 80, 95]])

In [53]:
a2[[0, 2],[0, 1]]   

array([ 4, 80])

In [58]:
a2[0,2], a2[0,1]

(6, 5)

## 배열 조건문
- pandas 문법과 유사하다 

In [62]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [69]:
[a>3]

[array([False, False, False,  True,  True,  True])]

In [71]:
a % 2 == 0 # 실무에서는 이런 코드를 작성하는 것이 핵심

array([False,  True, False,  True, False,  True])

# 배열의 슬라이싱 

In [101]:
# p 234
b1 = np.array([0,1,2,3,4,5])
print(b1)
b1[1:4]

[0 1 2 3 4 5]


array([1, 2, 3])

In [78]:
b1[:3]

array([0, 1, 2])

In [80]:
b1[2:]

array([2, 3, 4, 5])

In [98]:
b1[0:4:2]

array([0, 2])

In [105]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [107]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [118]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [121]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [124]:
b2[1:, 1:]

array([[50, 60],
       [80, 90]])

In [126]:
nums = [1,2,3, ['a', 'b']]
nums[3][0]

'a'

In [130]:
b2[1][1:3]

array([50, 60])

## Numpy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건문

In [134]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90
np.where(arr < 5, arr, arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [141]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
# 100, 101, 2, 3, 4, 5, 12, 14, 16, 18
# 2 미만 일 때는 100을 더한다.
# 5 초과 일 때는 2를 곱한다.

# 조건식과 대응되는 결과를 리스트로 만들기
cond_list = [arr > 5, arr < 2]
choice_list = [arr * 2, arr + 100]
np.select(cond_list, choice_list, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])