## NumPy
- 선형대수, 행렬 수치연산과 관련된 라이브러리
- 문과생, 고졸인데, 전문대졸인데... 선형대수는 모르는데요?
    + 선형대수를 공부해야 합니까?


- NumPy 기반으로 ==> 통계, 머신러닝, 등등 

In [1]:
# !pip install numpy

In [2]:
import streamlit as st

print(st.__version__)

ModuleNotFoundError: No module named 'streamlit'

In [4]:
import numpy as np # NumPy 라이브러리를 불러오기 

print(np.__version__)

1.26.2


In [6]:
num1 = [1, 2, 3, 4]
num2 = [3, 4, 5, 6]

num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [8]:
arr1 = np.array(num1)
arr2 = np.array(num2)
arr1

array([1, 2, 3, 4])

In [9]:
arr2

array([3, 4, 5, 6])

In [10]:
arr1 + arr2

array([ 4,  6,  8, 10])

In [12]:
import numpy as np

# 배열 생성
arr = np.array([1, np.e, np.e**2, 10])

# 자연로그 계산
log_arr = np.log(arr)

print("원래 배열:", arr)
print("자연로그 계산된 배열:", log_arr)

원래 배열: [ 1.          2.71828183  7.3890561  10.        ]
자연로그 계산된 배열: [0.         1.         2.         2.30258509]


In [14]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [16]:
a1.dtype # Python int  # Numpy int8, int16, int32, int64

dtype('int32')

In [18]:
np.array([0.5, 2, 0.01, 8]).dtype

dtype('float64')

## NumPy 배열 생성 
- 1차원, 2차원, 3차원.. 배열 생성

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10) # 1차원 배열, 2차원 또는 3차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [35]:
b2 = np.arange(5)
b2.shape

(5,)

In [40]:
# 범위의 시작과 끝 정하기 배열 생성
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [42]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [44]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [47]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

## NumPy 기초 문법 배우는 이유
- 문과생 : 데이터 분석가, 기초문법 있구나! 넘어가면 끝.
- 이공계 : 수치연산, 배열, 수식을 활용해서 문제 풀이
    + 클래스, 딥러닝 클래스, NumPy를 활용해서 딥러닝 알고리즘을 적용해서 클래스 & 라이브러리
    + 밑바닥부터 시작하는 딥러닝3, 

In [50]:
# 단위행렬
arr_I = np.eye(3)
arr_I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
arr_I.shape

(3, 3)

In [54]:
np.array(['1.5', '0.62']) # 데이터 형변환

array(['1.5', '0.62'], dtype='<U4')

In [57]:
# astype() # pandas에서 사용가능
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

In [59]:
np.array(['1.5', '0.62'], dtype = float)

array([1.5 , 0.62])

In [63]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1

array([10, 21,  0,  4,  5])

In [65]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(float)
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [70]:
# p.224
# 난수 무작위로 숫자를 추출한다

np.random.rand(2, 2, 4) # 0 ~ 1 사이의 실수 난수를 갖음

array([[[0.48010198, 0.16029575, 0.73040368, 0.59519409],
        [0.55167095, 0.90776462, 0.46342539, 0.00123712]],

       [[0.84668455, 0.91301339, 0.00746764, 0.37612191],
        [0.17570518, 0.61870348, 0.8149266 , 0.79773169]]])

In [89]:
np.random.randint(1, 100, 10)

array([44,  3, 98, 91,  8, 17, 59, 36, 24, 48])

In [90]:
# 리스트 생성
my_list = [1, 2, 2, 3, 3, 3]

# 리스트를 set으로 변환
my_set = set(my_list)

print("중복 제거된 set:", my_set)

중복 제거된 set: {1, 2, 3}


## 

In [2]:
import numpy as np
print(np.__version__)

1.26.2


In [7]:
import numpy 

print(numpy.__version__)

1.26.2


In [3]:
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

## 분석 프로젝트 진행 시
- 간단하고, 빠르게 하고 싶다! Google Colab 유용
- 2-3주 내내, 로컬 환경에서 분석을 하는 것이 훨씬 효율적

## 배열의 연산 
- p.225

In [4]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2) # 덧셈
print(arr1 - arr2) # 뺄셈
print(arr1 * arr2) # 곱셈
print(arr1 / arr2) # 나눗셈

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


## 비교연산

In [6]:
arr1 > 20

array([False, False,  True,  True])

## 통계 연산
- NumPy, 합, 평균, 표준 편차, 분산, 최솟값, 최댓값, 누적합, 누적 곱 메서드가 존재한다.
    + 기술통계량 (Descriptive Statistics) : 현재 데이터 상태를 표현(=묘사, Describe)한다.
- 통계 : 평균이 전부다! (Mean is Everything)

In [8]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [9]:
arr3.sum()

10

In [11]:
arr3.mean()

2.0

In [13]:
arr3.std() # 표준편차

1.4142135623730951

In [14]:
arr3.var() # 분산

2.0

## 누적합과 누적곱
- cumsum() : 누적합
- cumprod() : 누적곱

In [16]:
arr4 = np.arange(1, 5)
arr4

array([1, 2, 3, 4])

In [18]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [19]:
arr4.cumprod()

array([ 1,  2,  6, 24])

## 행렬연산
- 선형 대수(Linear Algebra)를 위한 2차원 배열 연산도 지원
- p229, 행렬곱, 전치행렬, 역행렬, 행렬식 사용 예시

In [21]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [23]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [25]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [27]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [28]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## 배열의 인덱싱과 슬라이싱 (p.230)
- string, list, tuple과 동일한 방법으로 접근

In [30]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [33]:
a1[4]

40

In [35]:
# 50을 70으로 변경하고 싶음
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [39]:
# 리스트 통해서 추출
a1[[0, 2, 4]]

array([ 0, 20, 40])

In [40]:
idx_list = [0, 2, 4]
a1[idx_list]

array([ 0, 20, 40])

In [41]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
a2[1, 1]

50

In [49]:
# 90을 95로 변경
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [58]:
a2[0] = [1, 2, 3] # 좋은 코드는 아니다! 
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 95]])

In [60]:
a2[0] = np.array([4, 5, 6]) # 정석
a2

array([[ 4,  5,  6],
       [40, 50, 60],
       [70, 80, 95]])

In [61]:
a2[0] = np.array([4, 5, 6, 7]) # 에러 확인, 이유 생각
a2

ValueError: could not broadcast input array from shape (4,) into shape (3,)

- 2차원 배열의 행과 열 위치 지정해서 원소 추출
  + (행의 위치1, 열의 위치1) / 행의 위치 2, 열의 위치2)

In [65]:
a2

array([[ 4,  5,  6],
       [40, 50, 60],
       [70, 80, 95]])

In [75]:
a2[[0, 2], [1, 1]]

array([ 5, 80])

In [74]:
a2[0, 0], a2[2, 1]

(4, 80)

## 배열 조건문
- pandas 문법과 유사하다

In [80]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [82]:
[a>3]

[array([False, False, False,  True,  True,  True])]

In [83]:
a[a>3]

array([4, 5, 6])

In [84]:
a % 2 == 0 # 실무에서는 이런 코드를 작성하는 것이 핵심!!! 

array([False,  True, False,  True, False,  True])